### ISSUE TITLE
MsgPack big endian?

### ISSUE THREAD

**Issue by rfyiamcool** [msgpack/msgpack#230] opened 2017-07-09 03:54 UTC
Not really an issue per se, but I'm writing a small encoder/decoder and I must say, it's a pain having to tansform all my in-memory representations of ints, floats from little-endian to big-endian.

**Comment by drewnoakes** [comment] 2017-10-23 15:19
Looks like a duplicate of #172.

**Comment by tagomoris** [comment] 2017-10-23 16:40
See https://github.com/msgpack/msgpack/issues/172#issuecomment-40641830

**Closed by tagomoris** 2017-10-23 16:40 UTC
